### ISSUE TITLE
Add Amino message implementation for claim

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#382]
At the moment, no Amino message implementation is available for the claim tx.
For this reason, users using a ledger could have errors in claiming the MerkleDrop.
We need to fix it.

**Comment by angelorc** [comment]
@DavideSegullo how we can fix it?

**Comment by DavideSegullo** [comment]
@angelorc I am looking for a solution, I am currently getting the following error:

`Uncaught (in promise) Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (24262), sequence (41) and chain-id (bitsong-2b): unauthorized
    at SigningStargateClient.broadcastTx (stargateclient.ts:375:13)
    at async TransactionManager.createSignBroadcast (transaction-manager.ts:274:10)`
